#Create file by using Ansible Script
---
- hosts: all
  gather_facts: no
  remote_user: ansible
  tasks:
    name: create file on remote/host server
    file:
      path: /tmp/data.txt
      state: touch
      mode: 775
      user: ansible

